config/routes.rb
Prefectura::Application.routes.draw do

  resources :posiciones

   root :to => 'posiciones#new'

end

app/models/DummyClass.rb
class DummyClass
end

app/models/origen_de_reporte.rb
class OrigenDeReporte < ActiveRecord::Base
end
# == Schema Information
#
# Table name: origenes_de_reporte
#
#  id         :integer         not null, primary key
#  codigo     :string(255)
#  etiqueta   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/models/urlws.rb
class Urlws < ActiveRecord::Base
end
# == Schema Information
#
# Table name: urlws
#
#  id         :integer         not null, primary key
#  url        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include WsHelper
end

app/controllers/posiciones_controller.rb
#encoding: utf-8

class PosicionesController < ApplicationController

  def new
    @OrigenesDeReporte = OrigenDeReporte.all
    @title = 'Home'
  end

  def create
    @cod = params[:reporte][:codigo]
    @ano = params[:reporte]["fecha(1i)"]
    @mes = params[:reporte]["fecha(2i)"]
    @dia = params[:reporte]["fecha(3i)"]

    unless @cod.blank? || @ano.blank? || @mes.blank? || @dia.blank?
      @fechaString = "#{@ano.to_s}-#{@mes.to_s}-#{@dia.to_s}"
      @fec = Chronic.parse(@fechaString)
      @fecFormateada = @fec.strftime("%d-%m-%y")
      @url = Urlws.first.url
      @respuestaWS = obtenerDatosdelWS(@cod, @fecFormateada, @url)
      unless @respuestaWS.blank?
        @listado = obtenerListadoEnArray(@respuestaWS)
        require 'dbi'
        require 'odbc_utf8'
        @dbh = DBI.connect('DBI:ODBC:rubydbf','','') #  Connect to a database, old style
        registro=Basedbf.new
        @listado.each do |valor| 
          mensaje=registro.insertar("pnanove", valor, @dbh)
        end
        flash[:success] = "Se obtenido la información exitosamente"
        redirect_to root_path
      end
    else
      @OrigenesDeReporte = OrigenDeReporte.all
      flash.now[:error] = 'Ha ocurrido un error al obtener los datos'
      render 'new'
    end
  end

end

app/helpers/Basedbf.rb
class Basedbf

  def insertar (nombre_base, registro_dato, dbh)
    @nombre_base=nombre_base	
    @registro_dato=registro_dato
    campo=[]
    campo=registro_dato

    registro_base = dbh.prepare( "INSERT INTO #{nombre_base}(columna1,
                   columna2,columna3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,
                                                                         columna11,columna12,columna13,columna14,columna15,columna16,columna17,columna18,columna19,columna20,
                                                                         columna21,columna22,columna23,columna24,columna25,columna26,columna27,columna28,columna29,columna30,columna31,columna32)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)" )
                   registro_base.execute(campo[0]	, campo[1], campo[2], campo[3], campo[4],campo[5],
                                         campo[6],campo[7], campo[8],campo[9], campo[10], campo[11], campo[12], campo[13],
                                         campo[14], campo[15], campo[16], campo[17], campo[18], campo[19], campo[20], campo[21],
                                         campo[22], campo[23],campo[24], campo[25], campo[26], campo[27], campo[28], campo[29], campo[30], campo[31])		   

                   registro_base.finish  # si no pongo esto sale el sig mensaje
                   # (WARNING: #<ODBC::Statement:0x1d2cff8> was not dropped before garbage collection)

                   msg='Registro ingresado'

                   return msg


  end
end

app/helpers/WS_helper.rb
module WsHelper

  def retornarHash(xml)
    Hash.from_xml(xml).with_indifferent_access
  end

  def obtenerDatosdelWS(reportName, fecha, url)
    client = Savon::Client.new(url)
    client.http.read_timeout = 500
    client.http.open_timeout = 500
    response = client.request :get_report do |soap|
      soap.body = {"report_name" => reportName, "report_params" => {"ReportParam" => {"nombre" => "fecha", "valor" => fecha, :attributes! => { "ins0:valor" => { "xsi:type" => "xsd:string"} } } } }
    end
    response.to_xml
  end

  def obtenerListadoEnArray(xml)
    @xml = retornarHash(xml)
    @registros = @xml[:Envelope][:Body][:GetReportResponse][:GetReportResult][:diffgram][:NewDataSet][:Table]
    @encabezados = ["msdata:rowOrder", "FH_INFO", "HS_INFO", "PT_INFO", "MATRICULA", "SDIST", "NRO_OMI", "IDEN", "PT_ORIG", "PT_DESTINO", "TIPO_MOV", "PT_FINAL", "EN_VIAJE", "NOMBRE", "UNIDAD", "KM", "CARGA", "OBSERVAC", "BAND", "ARQUEO_NETO", "CALADO_MAX", "CALADOR", "SERN", "TIPO_EVENTO", "COMENTARIO", "ID_VIAJE", "ID_ETAPA", "NRO_ETAPA", "ID_EVENTO", "REMOLCADA_POR", "ORIGEN", "DESTINO"]
    @resultado = []
    @registros.each do |registro| 
      @valores = []
      @encabezados.each do |encabezado| 
        @valores << registro[encabezado]
      end
      @resultado << @valores
    end
    return @resultado
  end

  #  def formatearFecha(fecha)
  #    fecha.strftime("%d-%m-%y")
  #  end

  def obtenerFecha(nombreDeCampo, params)
    @fecha = Date.new(params["#{nombreDeCampo.to_s}(1i)"].to_i, 
                      params["#{nombreDeCampo.to_s}(2i)"].to_i, 
                      params["#{nombreDeCampo.to_s}(3i)"].to_i)
    #   formatearFecha @fecha
  end

end

app/helpers/WS_helperSpike.rb
module WsHelperSpike
	def retornarHash(xml)
		Hash.from_xml(xml).with_indifferent_access
	end

	def obtenerLosValoresPorNokogiri(xml)
		require 'nokogiri'
		obtenerValoresDeXML(Nokogiri::XML(xml).to_xml)
	end


	def obtenerValoresDeXML(xml)
		@xml = retornarHash(xml)
		@registros = @xml[:Envelope][:Body][:GetReportResponse][:GetReportResult][:diffgram][:NewDataSet][:Table]
		@registros.map do |registro| registro.values end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logo
    image_tag("hidrovia.gif", :alt => "taesa", :class => "round")
  end

  def title
    base_title = "COPRE"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/ws_helper.rb
module WsHelper

	def retornarHash(xml)
		Hash.from_xml(xml).with_indifferent_access
	end

	# def obtenerDatosdelWS(reportName, fecha, url)
	#   client = Savon::Client.new(url)
	#   client.http.read_timeout = 500
	#   client.http.open_timeout = 500
	#   response = client.request :get_report do |soap|
	#     soap.body = {"report_name" => reportName, "report_params" => {"ReportParam" => {"nombre" => "fecha", "valor" => fecha, :attributes! => { "ins0:valor" => { "xsi:type" => "xsd:string"} } } } }
	#   end
	#   response.to_xml
	# end

	def obtenerDatosdelWS(reportName, fecha, url)
		# @response = HTTParty.get('http://stark-cove-7785.herokuapp.com/posiciones/index.xml?fecha=15-09-13&reportName=Hidrovia_PZRP')
		@response = HTTParty.get(url, :query => {:fecha => fecha, :reportName => reportName})
		@response.body
	end

	def obtenerListadoEnArray(xml)
		@xml = retornarHash(xml)
		@registros = @xml[:Envelope][:Body][:GetReportResponse][:GetReportResult][:diffgram][:NewDataSet][:Table]
		@encabezados = ["msdata:rowOrder", "FH_INFO", "HS_INFO", "PT_INFO", "MATRICULA", "SDIST", "NRO_OMI", "IDEN", "PT_ORIG", "PT_DESTINO", "TIPO_MOV", "PT_FINAL", "EN_VIAJE", "NOMBRE", "UNIDAD", "KM", "CARGA", "OBSERVAC", "BAND", "ARQUEO_NETO", "CALADO_MAX", "CALADOR", "SERN", "TIPO_EVENTO", "COMENTARIO", "ID_VIAJE", "ID_ETAPA", "NRO_ETAPA", "ID_EVENTO", "REMOLCADA_POR", "ORIGEN", "DESTINO"]
		@resultado = []
		@registros.each do |registro| 
			@valores = []
			@encabezados.each do |encabezado| 
				@valores << registro[encabezado]
			end
			@resultado << @valores
		end
		return @resultado
	end

	#  def formatearFecha(fecha)
	#    fecha.strftime("%d-%m-%y")
	#  end

	def obtenerFecha(nombreDeCampo, params)
		@fecha = Date.new(params["#{nombreDeCampo.to_s}(1i)"].to_i, 
											params["#{nombreDeCampo.to_s}(2i)"].to_i, 
											params["#{nombreDeCampo.to_s}(3i)"].to_i)
		#   formatearFecha @fecha
	end

end

app/views/layouts/_header.html.erb
<header>
<%= link_to logo, root_path %>
<nav class="round">
<ul>
  <li><%= link_to "Home", root_path %></li>
</ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :application %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
      <% end %>
      <%= yield %>
      </section>
      <%= debug(params) if Rails.env.development? || Rails.env.test? %>
    </div>
  </body>
</html>

app/views/posiciones/new.html.erb
<%= form_for(:reporte, :url => posiciones_path) do |f| %>
  <div class="field">
    <%= f.label :reporte %> <br />
    <%= f.collection_select(:codigo, @OrigenesDeReporte, :codigo, :etiqueta) %>
  </div>
  <div class="field">
    <%= f.label :fecha %> <br />
    <%= f.date_select :fecha, :order => [ :day, :month, :year ], :use_month_numbers => true  %>  
  </div>
  <div class="actions">
    <%= f.submit "Obtener reporte" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>